[programs.devnet]
myepicproject = "HEbpuQwwgdkNYMzwo2QK5dDhQikwYK3MXz1xrx7LnZdZ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/femi/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
